services:
  postgres:
    image: postgres:17
    container_name: fitness-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: fitness
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fitness

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fitness-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: fitness-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

  api:
    container_name: fitness-api

    build:
      context: .
      dockerfile: Backend/src/Fitness.API/Dockerfile

    restart: unless-stopped

    ports:
      - "5000:8080"

    depends_on:
      - postgres
      - redis

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=fitness;Username=fitness;Password=123456

      Redis__ConnectionString: redis:6379
volumes:
  postgres_data:
  redis_data:

  